package entity;
// Generated 27.06.2016 09:55:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Adresse generated by hbm2java
 */
public class Adresse  implements java.io.Serializable {


     private Integer id;
     private String ort;
     private String plz;
     private String strasse;
     private String nummer;
     private Set benutzers = new HashSet(0);

    public Adresse() {
    }

    public Adresse(String ort, String plz, String strasse, String nummer, Set benutzers) {
       this.ort = ort;
       this.plz = plz;
       this.strasse = strasse;
       this.nummer = nummer;
       this.benutzers = benutzers;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getOrt() {
        return this.ort;
    }
    
    public void setOrt(String ort) {
        this.ort = ort;
    }
    public String getPlz() {
        return this.plz;
    }
    
    public void setPlz(String plz) {
        this.plz = plz;
    }
    public String getStrasse() {
        return this.strasse;
    }
    
    public void setStrasse(String strasse) {
        this.strasse = strasse;
    }
    public String getNummer() {
        return this.nummer;
    }
    
    public void setNummer(String nummer) {
        this.nummer = nummer;
    }
    public Set getBenutzers() {
        return this.benutzers;
    }
    
    public void setBenutzers(Set benutzers) {
        this.benutzers = benutzers;
    }




}


