package entity;
// Generated 27.06.2016 09:55:21 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Artikel generated by hbm2java
 */
public class Artikel  implements java.io.Serializable {


     private Integer id;
     private Hoerertyp hoerertyp;
     private Steckertyp steckertyp;
     private BigDecimal preis;
     private String boxendurchmesser;
     private Set bestellungartikels = new HashSet(0);

    public Artikel() {
    }

	
    public Artikel(Hoerertyp hoerertyp, Steckertyp steckertyp) {
        this.hoerertyp = hoerertyp;
        this.steckertyp = steckertyp;
    }
    public Artikel(Hoerertyp hoerertyp, Steckertyp steckertyp, BigDecimal preis, String boxendurchmesser, Set bestellungartikels) {
       this.hoerertyp = hoerertyp;
       this.steckertyp = steckertyp;
       this.preis = preis;
       this.boxendurchmesser = boxendurchmesser;
       this.bestellungartikels = bestellungartikels;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Hoerertyp getHoerertyp() {
        return this.hoerertyp;
    }
    
    public void setHoerertyp(Hoerertyp hoerertyp) {
        this.hoerertyp = hoerertyp;
    }
    public Steckertyp getSteckertyp() {
        return this.steckertyp;
    }
    
    public void setSteckertyp(Steckertyp steckertyp) {
        this.steckertyp = steckertyp;
    }
    public BigDecimal getPreis() {
        return this.preis;
    }
    
    public void setPreis(BigDecimal preis) {
        this.preis = preis;
    }
    public String getBoxendurchmesser() {
        return this.boxendurchmesser;
    }
    
    public void setBoxendurchmesser(String boxendurchmesser) {
        this.boxendurchmesser = boxendurchmesser;
    }
    public Set getBestellungartikels() {
        return this.bestellungartikels;
    }
    
    public void setBestellungartikels(Set bestellungartikels) {
        this.bestellungartikels = bestellungartikels;
    }




}


