package entity;
// Generated 27.06.2016 09:55:21 by Hibernate Tools 4.3.1



/**
 * Benutzerbestellung generated by hbm2java
 */
public class Benutzerbestellung  implements java.io.Serializable {


     private Integer id;
     private Benutzer benutzer;
     private Bestellung bestellung;

    public Benutzerbestellung() {
    }

    public Benutzerbestellung(Benutzer benutzer, Bestellung bestellung) {
       this.benutzer = benutzer;
       this.bestellung = bestellung;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Benutzer getBenutzer() {
        return this.benutzer;
    }
    
    public void setBenutzer(Benutzer benutzer) {
        this.benutzer = benutzer;
    }
    public Bestellung getBestellung() {
        return this.bestellung;
    }
    
    public void setBestellung(Bestellung bestellung) {
        this.bestellung = bestellung;
    }




}


