package entity;
// Generated 27.06.2016 09:55:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Benutzer generated by hbm2java
 */
public class Benutzer  implements java.io.Serializable {


     private Integer id;
     private Adresse adresse;
     private String benutzer;
     private String passwort;
     private Boolean admin;
     private Set benutzerbestellungs = new HashSet(0);

    public Benutzer() {
    }

	
    public Benutzer(String benutzer, String passwort) {
        this.benutzer = benutzer;
        this.passwort = passwort;
    }
    public Benutzer(Adresse adresse, String benutzer, String passwort, Boolean admin, Set benutzerbestellungs) {
       this.adresse = adresse;
       this.benutzer = benutzer;
       this.passwort = passwort;
       this.admin = admin;
       this.benutzerbestellungs = benutzerbestellungs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Adresse getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(Adresse adresse) {
        this.adresse = adresse;
    }
    public String getBenutzer() {
        return this.benutzer;
    }
    
    public void setBenutzer(String benutzer) {
        this.benutzer = benutzer;
    }
    public String getPasswort() {
        return this.passwort;
    }
    
    public void setPasswort(String passwort) {
        this.passwort = passwort;
    }
    public Boolean getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Boolean admin) {
        this.admin = admin;
    }
    public Set getBenutzerbestellungs() {
        return this.benutzerbestellungs;
    }
    
    public void setBenutzerbestellungs(Set benutzerbestellungs) {
        this.benutzerbestellungs = benutzerbestellungs;
    }




}


