package entity;
// Generated 27.06.2016 09:55:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bestellung generated by hbm2java
 */
public class Bestellung  implements java.io.Serializable {


     private Integer id;
     private Rabatte rabatte;
     private Boolean bestellt;
     private Set rechnungs = new HashSet(0);
     private Set bestellungartikels = new HashSet(0);
     private Set benutzerbestellungs = new HashSet(0);

    public Bestellung() {
    }

    public Bestellung(Rabatte rabatte, Boolean bestellt, Set rechnungs, Set bestellungartikels, Set benutzerbestellungs) {
       this.rabatte = rabatte;
       this.bestellt = bestellt;
       this.rechnungs = rechnungs;
       this.bestellungartikels = bestellungartikels;
       this.benutzerbestellungs = benutzerbestellungs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Rabatte getRabatte() {
        return this.rabatte;
    }
    
    public void setRabatte(Rabatte rabatte) {
        this.rabatte = rabatte;
    }
    public Boolean getBestellt() {
        return this.bestellt;
    }
    
    public void setBestellt(Boolean bestellt) {
        this.bestellt = bestellt;
    }
    public Set getRechnungs() {
        return this.rechnungs;
    }
    
    public void setRechnungs(Set rechnungs) {
        this.rechnungs = rechnungs;
    }
    public Set getBestellungartikels() {
        return this.bestellungartikels;
    }
    
    public void setBestellungartikels(Set bestellungartikels) {
        this.bestellungartikels = bestellungartikels;
    }
    public Set getBenutzerbestellungs() {
        return this.benutzerbestellungs;
    }
    
    public void setBenutzerbestellungs(Set benutzerbestellungs) {
        this.benutzerbestellungs = benutzerbestellungs;
    }




}


