package entity;
// Generated 27.06.2016 09:55:21 by Hibernate Tools 4.3.1



/**
 * Bestellungartikel generated by hbm2java
 */
public class Bestellungartikel  implements java.io.Serializable {


     private Integer id;
     private Artikel artikel;
     private Bestellung bestellung;
     private Integer anzahl;

    public Bestellungartikel() {
    }

    public Bestellungartikel(Artikel artikel, Bestellung bestellung, Integer anzahl) {
       this.artikel = artikel;
       this.bestellung = bestellung;
       this.anzahl = anzahl;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Artikel getArtikel() {
        return this.artikel;
    }
    
    public void setArtikel(Artikel artikel) {
        this.artikel = artikel;
    }
    public Bestellung getBestellung() {
        return this.bestellung;
    }
    
    public void setBestellung(Bestellung bestellung) {
        this.bestellung = bestellung;
    }
    public Integer getAnzahl() {
        return this.anzahl;
    }
    
    public void setAnzahl(Integer anzahl) {
        this.anzahl = anzahl;
    }




}


