package entity;
// Generated 27.06.2016 09:55:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rabatte generated by hbm2java
 */
public class Rabatte  implements java.io.Serializable {


     private Integer id;
     private String grund;
     private String code;
     private Integer prozentsatz;
     private Set bestellungs = new HashSet(0);

    public Rabatte() {
    }

    public Rabatte(String grund, String code, Integer prozentsatz, Set bestellungs) {
       this.grund = grund;
       this.code = code;
       this.prozentsatz = prozentsatz;
       this.bestellungs = bestellungs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getGrund() {
        return this.grund;
    }
    
    public void setGrund(String grund) {
        this.grund = grund;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public Integer getProzentsatz() {
        return this.prozentsatz;
    }
    
    public void setProzentsatz(Integer prozentsatz) {
        this.prozentsatz = prozentsatz;
    }
    public Set getBestellungs() {
        return this.bestellungs;
    }
    
    public void setBestellungs(Set bestellungs) {
        this.bestellungs = bestellungs;
    }




}


