package entity;
// Generated 27.06.2016 09:55:21 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Rechnung generated by hbm2java
 */
public class Rechnung  implements java.io.Serializable {


     private Integer id;
     private Bestellung bestellung;
     private BigDecimal betrag;
     private Date zahldatum;

    public Rechnung() {
    }

    public Rechnung(Bestellung bestellung, BigDecimal betrag, Date zahldatum) {
       this.bestellung = bestellung;
       this.betrag = betrag;
       this.zahldatum = zahldatum;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Bestellung getBestellung() {
        return this.bestellung;
    }
    
    public void setBestellung(Bestellung bestellung) {
        this.bestellung = bestellung;
    }
    public BigDecimal getBetrag() {
        return this.betrag;
    }
    
    public void setBetrag(BigDecimal betrag) {
        this.betrag = betrag;
    }
    public Date getZahldatum() {
        return this.zahldatum;
    }
    
    public void setZahldatum(Date zahldatum) {
        this.zahldatum = zahldatum;
    }




}


