package entity;
// Generated 27.06.2016 09:55:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Steckertyp generated by hbm2java
 */
public class Steckertyp  implements java.io.Serializable {


     private Integer id;
     private String bezeichnung;
     private Set artikels = new HashSet(0);

    public Steckertyp() {
    }

    public Steckertyp(String bezeichnung, Set artikels) {
       this.bezeichnung = bezeichnung;
       this.artikels = artikels;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getBezeichnung() {
        return this.bezeichnung;
    }
    
    public void setBezeichnung(String bezeichnung) {
        this.bezeichnung = bezeichnung;
    }
    public Set getArtikels() {
        return this.artikels;
    }
    
    public void setArtikels(Set artikels) {
        this.artikels = artikels;
    }




}


